version: "2"
services:
  registry:
    build: ./registry-service
    networks:
      - swos
    ports:
      - "1111:1111"
  person:
    build: ./person-service
    networks:
      - swos
  address:
    build: ./address-service
    networks:
      - swos
  person-address:
    build: ./person-address-service
    networks:
      - swos
  frontend:
    build: ./frontend-service
    networks:
      - swos
    ports:
      - "8080:8080"
  monitor:
    build: ./monitor-service
    networks:
      - swos
    ports:
      - "9999:9999"
networks:
  swos: