# Configure this Discovery Server
eureka:
  server:
    #eviction-interval-timer-in-ms: 20000
    enableSelfPreservation: false
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111   # HTTP (Tomcat) port