# Spring properties
spring:
  application:
    name: address-service
  h2:
    console:
      enabled: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
